import DashboardLayout from '@/components/layout/DashboardLayout';
import ActivityLogFeed from '@/modules/activityLogs/ActivityLogFeed';

export default function ActivityLogsPage() {
  return (
    <DashboardLayout>
      <div className="p-8 space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-gray-900">Activity Logs</h1>
            <p className="text-gray-500">Review the recent activity generated by your account.</p>
          </div>
        </div>
        <ActivityLogFeed />
      </div>
    </DashboardLayout>
  );
}
